name: Master Preview
on:
  push:
    branches: [master]

jobs:
  preview:
    runs-on: ubuntu-latest
    
    steps:
      - name: Checkout code
        uses: actions/checkout@v3
        with:
          fetch-depth: 0

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 18
          cache: 'npm'

      - name: Install dependencies
        run: |
          cd docusaurus
          npm ci

      - name: Build
        run: |
          cd docusaurus
          npm run build

      # Preview deployment adımları buraya eklenebilir
      # - name: Deploy Preview
      #   run: |
      #     # Preview deployment komutları
