name: PR Cleanup
on:
  pull_request:
    types: [closed]

jobs:
  cleanup:
    runs-on: ubuntu-latest
    if: github.event.pull_request.head.repo.full_name == github.repository

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Cleanup preview
        run: |
          echo "Cleaning up preview environment..."
          # Cleanup komutları buraya eklenebilir

      - name: Notify cleanup completion
        uses: actions/github-script@v6
        with:
          script: |
            const issue_number = context.issue.number;
            await github.rest.issues.createComment({
              owner: context.repo.owner,
              repo: context.repo.repo,
              issue_number: issue_number,
              body: '🧹 Preview environment cleaned up.'
            });
