# Continuous Deployment job to deploy the portal to the BigFile as an asset canister
# as well as to the Netlify thebigfile.com

name: CD

on:
  push:
    branches: [main, master]

  workflow_dispatch:

jobs:
  build-and-deploy:
    name: "Build & Deploy"
    runs-on: ubuntu-latest
    
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 18
          cache: 'npm'

      - name: Install dependencies
        run: npm ci

      - name: Build
        run: npm run build

      # Buraya deploy adımları eklenebilir
      # - name: Deploy
      #   run: |
      #     # Deploy komutları
