# Continuous Deployment job to deploy the portal to the BigFile as an asset canister
# as well as to the Netlify thebigfile.com

name: CD

on:
  push:
    branches: [master]

  repository_dispatch:
    types: redeploy

jobs:
  deploy-ic:
    name: "Deploy to BIG"
    runs-on: ubuntu-latest
    concurrency:
      group: "website update"
      cancel-in-progress: true
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v3
        with:
          node-version: 18
      - run: npm install
