# Continuous Deployment job to deploy the portal to the BigFile as an asset canister
# as well as to the Netlify thebigfile.com

name: CD

on:
  push:
    branches: [master]

  repository_dispatch:
    types: redeploy

jobs:
  deploy:
    name: "Deploy"
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v3
        with:
          node-version: 18
      - run: npm install
      - run: npm run build
